version: '3.8'

services:
  db:
    image: postgres:15 # VocÃª pode alterar a versÃ£o do Postgres se precisar
    container_name: postgres_db_social
    # Mapeia a porta 5435 (sua mÃ¡quina) para a 5432 (container)
    ports:
      - "5435:5432"
    # VariÃ¡veis de ambiente para configurar o banco
    environment:
      POSTGRES_USER: postgres     # ğŸ‘ˆ Troque pelo seu usuÃ¡rio
      POSTGRES_PASSWORD: postgres   # ğŸ‘ˆ Troque pela sua senha
      POSTGRES_DB: post_db # ğŸ‘ˆ Troque pelo nome do banco
    # Volume para persistir os dados mesmo se o container parar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  # Define o volume nomeado
  postgres-data:
    driver: local